spring.application.name=User-Service
server.port=9020
jwt.secretKey = asdfladf98a7df89aysf8d9yasiudfha9s87dfa89syudhfa98sdfyaisuhdfa98sfy

spring.datasource.url=jdbc:postgresql://localhost:5432/SociofyUsers
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=create-drop