spring.application.name=discovery-server

#default server for discovery server , if we want to use some other port then we need to configure it.
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false