spring.application.name=discovery-server

#default server for discovery server , if we want to use some other port then we need to configure it.
server.port=8761
# This is the default configuration for eureka server, if we want to use some other port then we need to configure it.
eureka.client.register-with-eureka=false 
# This is for the eureka server to not register itself with eureka server
eureka.client.fetch-registry=false
# This is to prevent the eureka server from downloading the registry from other eureka servers, as this is a standalone server.
